version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - export COMMIT_ID="${CODEBUILD_RESOLVED_SOURCE_VERSION}"
      - export ZIP_FILE_NAME="${CODEBUILD_BUILD_NUMBER}_${COMMIT_ID}"
      - echo "ZIP_FILE_NAME = $ZIP_FILE_NAME"
      
      - echo "***** Installing Ionic CLI *****"
      - npm install -g @ionic/cli

      - echo "***** Install Node Module *****"
      - npm install --force

      - |
         cat > buildDetails.txt <<- EOM 
         BUILD_NUMBER=${CODEBUILD_BUILD_NUMBER}
         COMMIT_ID=${COMMIT_ID}
         EOM
       
  build:
    commands:
      - ionic build --prod
  post_build:
    commands:
      - echo "***** Packaging Ionic Project *****"
      - cd www
      - zip -r ../$ZIP_FILE_NAME.zip *
      - cd ..
      - echo "***** Packaging Ionic Project Completed *****"
artifacts:
  files:
    - $ZIP_FILE_NAME.zip